// packages/react-test-app/src/preview-examples/time-input.tsx
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { IxTimeInput } from '@siemens/ix-react';


import React, { useRef, useState } from 'react';

export default function TimeInputExample() {
  const timeInputRef = useRef<any>(null);
  const [touched, setTouched] = useState(false);
  const [value, setValue] = useState('');
  const [valid, setValid] = useState(false);
  const [invalid, setInvalid] = useState(false);
  const [inputInvalid, setInputInvalid] = useState(false);

  const handleValueChange = (event: CustomEvent<string>) => {
    const val = event.detail ?? '';
    setValue(val);
    setTouched(true);
    // Simple validation: valid if not empty and not 'invalid'
    setValid(!!val && val !== 'invalid');
    setInvalid(!val || val === 'invalid');
    setInputInvalid(!val || val === 'invalid');
  };

  const setEmptyProgrammatically = () => {
    if (timeInputRef.current) {
      timeInputRef.current.value = '';
      setTouched(true);
      setValue('');
      setValid(false);
      setInvalid(true);
      setInputInvalid(true);
    }
  };

  const resetValue = () => {
    if (timeInputRef.current) {
      timeInputRef.current.value = null;
      setTouched(false);
      setValue('');
      setValid(true);
      setInvalid(false);
      setInputInvalid(false);
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    console.log('Form submitted:', { touched, value, valid, invalid, inputInvalid });
  };

  return (
    <form novalidate onSubmit={handleSubmit}>
      <IxTimeInput required ref={timeInputRef} onValueChange={handleValueChange} />
      <div style={{ marginTop: '1rem' }}>
        <button type="button" onClick={setEmptyProgrammatically}>
          Set Empty Programmatically
        </button>
        <button type="button" onClick={resetValue}>
          Reset Value (remove touched state)
        </button>
        <button type="submit">Submit</button>
      </div>
      <div style={{ marginTop: '1rem' }}>
        <div>Touched: {String(touched)}</div>
        <div>Value: {value}</div>
        <div>Valid: {String(valid)}</div>
        <div>Invalid: {String(invalid)}</div>
        <div>Input Invalid: {String(inputInvalid)}</div>
      </div>
    </form>
  );


}

// packages/angular-test-app/src/preview-examples/time-input.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import { FormControl } from '@angular/forms';

@Component({
  selector: 'app-example',
  templateUrl: './time-input.html',
})
export default class TimeInput {
  touched = false;
  value = '';
  valid = false;
  invalid = false;
  inputInvalid = false;

  onValueChange(event: any) {
    const val = event.detail ?? '';
    this.value = val;
    // Simple validation: valid if not empty and not 'invalid'
    this.valid = !!this.value && this.value !== 'invalid';
    this.invalid = !this.valid;
    this.inputInvalid = this.invalid;
    // Touched logic: if value changes by user, mark as touched
    this.touched = true;
  }

  /**
   * Simulates a user clearing the field (field is empty, touched, and invalid)
   */
  setEmptyProgrammatically(timeInput: any) {
    if (timeInput) {
      timeInput.value = '';
      this.touched = true;
      this.value = '';
      // Empty and touched is invalid
      this.valid = false;
      this.invalid = true;
      this.inputInvalid = true;
    }
  }

  /**
   * Simulates a true form reset (field is empty, untouched, and valid)
   */
  resetValue(timeInput: any) {
    if (timeInput) {
      timeInput.value = null;
      this.touched = false;
      this.value = '';
      // Empty and untouched is valid (no error shown)
      this.valid = true;
      this.invalid = false;
      this.inputInvalid = false;
    }
  }
}
