// packages/vue-test-app/src/preview-examples/radio-group.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { ref, onMounted, watch } from 'vue';
import { IxRadio, IxRadioGroup } from '@siemens/ix-vue';

const selectedStorage = ref('');
const touched = ref(false);
const error = ref('');

// Add watcher to debug value changes
watch(
  selectedStorage,
  (newVal, oldVal) => {
    console.log('=== VUE SELECTEDSTORAGE WATCHER ===');
    console.log('Old value:', oldVal);
    console.log('New value:', newVal);
    console.log('Type of new value:', typeof newVal);
    console.log('===================================');
  },
  { immediate: true }
);

const selectedStorage2 = ref('');
const touched2 = ref(false);
const error2 = ref('');

function validateSelection() {
  if (touched.value && !selectedStorage.value) {
    error.value = 'Please select a storage option';
  } else {
    error.value = '';
  }
}

function validateSelection2() {
  if (touched2.value && !selectedStorage2.value) {
    error2.value = 'Please select a storage option';
  } else {
    error2.value = '';
  }
}

function submitForm() {
  touched.value = true;
  validateSelection();
  if (!error.value) {
    alert('Form submitted: ' + selectedStorage.value);
  }
}

function submitForm2() {
  touched2.value = true;
  validateSelection2();
  if (!error2.value) {
    alert('Form 2 submitted: ' + selectedStorage2.value);
  }
}

function resetForm() {
  console.log('=== VUE FORM RESET ===');
  console.log('Before reset - selectedStorage.value:', selectedStorage.value);
  console.log('Before reset - type:', typeof selectedStorage.value);

  // Check the actual DOM element
  const radioGroup = radioGroupRef.value as any;
  if (radioGroup) {
    console.log('RadioGroup DOM element value before:', radioGroup.value);
  }

  selectedStorage.value = null as any; // Try null instead of empty string

  // Check again after Vue update
  setTimeout(() => {
    if (radioGroup) {
      console.log('RadioGroup DOM element value after:', radioGroup.value);
    }
  }, 10);

  console.log('After reset - selectedStorage.value:', selectedStorage.value);
  console.log('After reset - type:', typeof selectedStorage.value);
  touched.value = false;
  error.value = '';
  console.log('Reset completed');
  console.log('====================');
}

function resetForm2() {
  console.log('=== VUE FORM 2 RESET ===');
  console.log('Before reset - selectedStorage2.value:', selectedStorage2.value);
  selectedStorage2.value = '';
  touched2.value = false;
  error2.value = '';
  console.log('Reset completed');
  console.log('======================');
}

function handleFormReset() {
  console.log('=== NATIVE FORM RESET EVENT ===');
  // Native form reset event - let's try to respond to this
  setTimeout(() => {
    console.log('Handling native reset - clearing Vue state');
    selectedStorage.value = '';
    touched.value = false;
    error.value = '';
  }, 0);
  console.log('===============================');
}

function handleFormReset2() {
  console.log('=== NATIVE FORM 2 RESET EVENT ===');
  setTimeout(() => {
    console.log('Handling native reset 2 - clearing Vue state');
    selectedStorage2.value = '';
    touched2.value = false;
    error2.value = '';
  }, 0);
  console.log('=================================');
}

function clearTouchedState() {
  touched.value = false;
  error.value = '';
}

const nativeForm = ref(null);
const vueForm = ref(null);
const vueForm2 = ref(null);
const radioGroupRef = ref(null);

function submitNativeForm() {
  const form = nativeForm.value as HTMLFormElement;
  const formData = new FormData(form);
  const selectedValue = formData.get('nativeStorage');

  if (selectedValue) {
    alert('Native form submitted: ' + selectedValue);
  } else {
    alert('Please select a storage option');
  }

  updateNativeDisplay();
}

function resetNativeForm() {
  console.log('=== NATIVE JS FORM RESET ===');
  const form = nativeForm.value as HTMLFormElement;
  if (form) {
    form.reset();
    console.log('Native form reset called via JS');
    updateNativeDisplay();
  }
  console.log('============================');
}

function updateNativeDisplay() {
  setTimeout(() => {
    const form = nativeForm.value as HTMLFormElement;
    if (form) {
      const formData = new FormData(form);
      const selectedValue = formData.get('nativeStorage') || 'None';
      const displayElement = document.getElementById('nativeValue');
      if (displayElement) {
        displayElement.textContent = selectedValue.toString();
      }
    }
  }, 10);
}

// Add event listeners for native radio buttons to update display
function setupNativeListeners() {
  setTimeout(() => {
    const form = nativeForm.value as HTMLFormElement;
    if (form) {
      const radios = form.querySelectorAll('input[name="nativeStorage"]');
      radios.forEach((radio) => {
        radio.addEventListener('change', updateNativeDisplay);
      });
      updateNativeDisplay(); // Initial update
    }
  }, 100);
}

// Setup listeners when component mounts
onMounted(() => {
  setupNativeListeners();
});
</script>

<template>
  <div style="padding: 20px; max-width: 600px; height: 500px; overflow: scroll">
    <h2>Radio Group - Form Reset Testing</h2>
    <form
      @submit.prevent="submitForm"
      style="
        border: 1px solid #ccc;
        padding: 15px;
        border-radius: 4px;
        margin-bottom: 20px;
      "
    >
      <h3>Storage Configuration Form</h3>
      <IxRadioGroup
        ref="radioGroupRef"
        label="Storage options"
        :value="selectedStorage"
        @value-change="
          console.log('=== VUE @value-change EVENT ===', $event.detail);
          selectedStorage = $event.detail;
          touched = true;
          validateSelection();
        "
        :class="{ 'ix-invalid': touched && !selectedStorage }"
        style="margin-bottom: 15px"
      >
        <IxRadio
          label="256GB SSD storage"
          value="256"
          name="selectedStorage"
          required
        />
        <IxRadio label="512GB SSD storage" value="512" name="selectedStorage" />
        <IxRadio label="1TB SSD storage" value="1024" name="selectedStorage" />
        <IxRadio
          label="2TB SSD storage"
          value="2048"
          name="selectedStorage"
          disabled
        />
      </IxRadioGroup>
      <div v-if="touched && error" style="color: red; margin-top: 8px">
        {{ error }}
      </div>
      <div style="margin-top: 20px">
        <button
          type="submit"
          style="
            padding: 8px 16px;
            background: #007bff;
            color: white;
            border: none;
            border-radius: 4px;
            margin-right: 10px;
          "
        >
          Submit Order
        </button>
        <button
          type="button"
          @click="resetForm"
          style="
            padding: 8px 16px;
            background: #6c757d;
            color: white;
            border: none;
            border-radius: 4px;
            margin-right: 10px;
          "
        >
          Reset Form
        </button>
        <button
          type="button"
          @click="clearTouchedState"
          style="
            padding: 8px 16px;
            background: #28a745;
            color: white;
            border: none;
            border-radius: 4px;
          "
        >
          Clear Touched State
        </button>
      </div>
      <div style="margin-top: 15px">
        <div>
          <strong>Current Value:</strong> {{ selectedStorage || 'None' }}
        </div>
        <div><strong>Touched:</strong> {{ touched }}</div>
      </div>
    </form>
    <!-- Standalone Radio Group (for comparison) -->
    <div
      style="
        border: 1px solid #ccc;
        padding: 15px;
        color: #333;
        border-radius: 4px;
        margin-bottom: 20px;
      "
    >
      <h3>Standalone Radio Group (No Form)</h3>
      <IxRadioGroup label="Storage options">
        <IxRadio
          label="256GB SSD storage"
          value="256"
          name="storage-standalone"
        />
        <IxRadio
          label="512GB SSD storage"
          value="512"
          name="storage-standalone"
        />
        <IxRadio
          label="1TB SSD storage"
          value="1024"
          name="storage-standalone"
        />
        <IxRadio
          label="2TB SSD storage"
          value="2048"
          name="storage-standalone"
          disabled
        />
      </IxRadioGroup>
    </div>

    <!-- Native HTML Radio Group (for comparison) -->
    <div style="border: 1px solid red; padding: 15px; border-radius: 4px">
      <h3>Native HTML Radio Group</h3>
      <form
        ref="nativeForm"
        @submit.prevent="submitNativeForm"
        style="
          border: 1px solid #ddd;
          padding: 10px;
          border-radius: 4px;
          background: #f9f9f9;
        "
      >
        <fieldset
          style="
            border: 1px solid #ccc;
            padding: 10px;
            border-radius: 4px;
            margin-bottom: 15px;
          "
        >
          <legend>Storage Options (Native HTML)</legend>
          <div style="margin-bottom: 8px">
            <input
              type="radio"
              id="native-256"
              name="nativeStorage"
              value="256"
              required
            />
            <label for="native-256" style="margin-left: 8px"
              >256GB SSD storage</label
            >
          </div>
          <div style="margin-bottom: 8px">
            <input
              type="radio"
              id="native-512"
              name="nativeStorage"
              value="512"
            />
            <label for="native-512" style="margin-left: 8px"
              >512GB SSD storage</label
            >
          </div>
          <div style="margin-bottom: 8px">
            <input
              type="radio"
              id="native-1024"
              name="nativeStorage"
              value="1024"
            />
            <label for="native-1024" style="margin-left: 8px"
              >1TB SSD storage</label
            >
          </div>
          <div style="margin-bottom: 8px">
            <input
              type="radio"
              id="native-2048"
              name="nativeStorage"
              value="2048"
              disabled
            />
            <label for="native-2048" style="margin-left: 8px"
              >2TB SSD storage (Disabled)</label
            >
          </div>
        </fieldset>

        <div style="margin-top: 15px">
          <button
            type="submit"
            style="
              padding: 8px 16px;
              background: #007bff;
              color: white;
              border: none;
              border-radius: 4px;
              margin-right: 10px;
            "
          >
            Submit Native Form
          </button>
          <button
            type="reset"
            style="
              padding: 8px 16px;
              background: #dc3545;
              color: white;
              border: none;
              border-radius: 4px;
              margin-right: 10px;
            "
          >
            Reset Native Form
          </button>
          <button
            type="button"
            @click="resetNativeForm"
            style="
              padding: 8px 16px;
              background: #6c757d;
              color: white;
              border: none;
              border-radius: 4px;
            "
          >
            JS Reset Native Form
          </button>
        </div>

        <div style="margin-top: 15px; font-size: 14px">
          <div>
            <strong>Selected Native Value:</strong>
            <span id="nativeValue">None</span>
          </div>
        </div>
      </form>
    </div>
  </div>
</template>

// packages/react-test-app/src/preview-examples/radio-group.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */


import React, { useState } from 'react';
import { IxRadio, IxRadioGroup } from '@siemens/ix-react';

const initialFormState = {
  selectedStorage: '',
  // customerName: '',
  // email: '',
};

const initialTouched = {
  selectedStorage: false,
  // customerName: false,
  // email: false,
};

export default function RadioGroupExample() {
  const [form, setForm] = useState(initialFormState);
  const [touched, setTouched] = useState(initialTouched);

  // Native radio group for comparison
  const [nativeValue, setNativeValue] = useState('256');
  const [nativeTouched, setNativeTouched] = useState(false);

  const isValid = form.selectedStorage;

  const handleRadioChange = (event: CustomEvent<string>) => {
    const value = event.detail;
    setForm((prev) => ({ ...prev, selectedStorage: value }));
    setTouched((prev) => ({ ...prev, selectedStorage: true }));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setTouched({ selectedStorage: true });

    console.log('====================================');
  };

  const handleReset = () => {
    console.log('=== FORM RESET ===');
    console.log('Before reset:', form);
    // Reset like Angular: reset to initial values
    setForm(initialFormState);
    setTouched(initialTouched);
    console.log('After reset:', initialFormState);
    console.log('==================');
  };

  const handleClearTouched = () => {
    setTouched(initialTouched);
    console.log('=== CLEAR TOUCHED STATE ===');
    console.log('All controls marked as untouched.');
    console.log('Values preserved:', form);
    console.log('============================');
  };

  // Native radio group handlers
  const handleNativeChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setNativeValue(e.target.value);
    setNativeTouched(true);
  };
  const handleNativeSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setNativeTouched(true);
    console.log('=== NATIVE RADIO GROUP FORM SUBMISSION ===');
    console.log('Form submitted with values:');
    console.log('Selected Storage:', nativeValue);
    console.log('Form Valid:', !!nativeValue);
    console.log('Form Touched:', nativeTouched);
  };
  const handleNativeReset = () => {
    setNativeValue('256');
    setNativeTouched(false);
  };

  return (
    <div style={{ padding: 20, maxWidth: 600, height: 700, overflow: 'scroll' }}>
      <h2>Radio Group - Form Reset Testing</h2>
      {/* Form with validation and reset */}
      <form onSubmit={handleSubmit} style={{ border: '1px solid #ccc', padding: 15, borderRadius: 4, marginBottom: 20 }}>
        <h3>Storage Configuration Form</h3>
        <IxRadioGroup label="Storage options" value={form.selectedStorage} onValueChange={handleRadioChange} style={{ marginBottom: 15 }}>
          <IxRadio label="256GB SSD storage" value="256" name="selectedStorage" />
          <IxRadio label="512GB SSD storage" value="512" name="selectedStorage" />
          <IxRadio label="1TB SSD storage" value="1024" name="selectedStorage" />
          <IxRadio label="2TB SSD storage" value="2048" name="selectedStorage" />
        </IxRadioGroup>

        <div style={{ marginTop: 20 }}>
          <button type="submit" style={{ padding: '8px 16px', background: '#007bff', color: 'white', border: 'none', borderRadius: 4, marginRight: 10 }}>
            Submit Order
          </button>
          <button type="button" onClick={handleReset} style={{ padding: '8px 16px', background: '#6c757d', color: 'white', border: 'none', borderRadius: 4, marginRight: 10 }}>
            Reset Form
          </button>
          <button type="button" onClick={handleClearTouched} style={{ padding: '8px 16px', background: '#28a745', color: 'white', border: 'none', borderRadius: 4 }}>
            Clear Touched State
          </button>
        </div>
        <div style={{ marginTop: 15 }}>
          <div><strong>Current Values:</strong></div>
          <div>Selected Storage: {form.selectedStorage || 'None'}</div>
          <div>Customer Name: {/* form.customerName || */ 'Empty'}</div>
          <div>Email: {/* form.email || */ 'Empty'}</div>
          <div>Form Valid: {isValid ? 'true' : 'false'}</div>
          <div>Form Touched: {Object.values(touched).some(Boolean) ? 'true' : 'false'}</div>
        </div>
      </form>

      {/* Standalone Radio Group (for comparison) */}
      <div style={{ border: '1px solid #ccc', padding: 15, borderRadius: 4 }}>
        <h3>Standalone Radio Group (No Form)</h3>
        <IxRadioGroup label="Storage options">
          <IxRadio label="256GB SSD storage" value="256" name="storage-standalone" />
          <IxRadio label="512GB SSD storage" value="512" name="storage-standalone" />
          <IxRadio label="1TB SSD storage" value="1024" name="storage-standalone" />
          <IxRadio label="2TB SSD storage" value="2048" name="storage-standalone" disabled />
        </IxRadioGroup>
      </div>

      {/* Native Radio Group Form (for comparison) */}
      <form onSubmit={handleNativeSubmit} style={{ border: '1px solid #28a745', padding: 15, borderRadius: 4, margin: '20px 0' }}>
        <h3>Native Radio Group (Angular Reactive Form)</h3>
        <div style={{ marginBottom: 15 }}>
          <label><input type="radio" name="nativeStorage" value="256" checked={nativeValue === '256'} onChange={handleNativeChange} required /> 256GB SSD storage</label><br />
          <label><input type="radio" name="nativeStorage" value="512" checked={nativeValue === '512'} onChange={handleNativeChange} required /> 512GB SSD storage</label><br />
          <label><input type="radio" name="nativeStorage" value="1024" checked={nativeValue === '1024'} onChange={handleNativeChange} required /> 1TB SSD storage</label><br />
          <label><input type="radio" name="nativeStorage" value="2048" checked={nativeValue === '2048'} onChange={handleNativeChange} required /> 2TB SSD storage</label>
        </div>
        <div style={{ marginTop: 20 }}>
          <button type="submit" style={{ padding: '8px 16px', background: '#28a745', color: 'white', border: 'none', borderRadius: 4, marginRight: 10 }}>
            Submit Native Form
          </button>
          <button type="button" onClick={handleNativeReset} style={{ padding: '8px 16px', background: '#6c757d', color: 'white', border: 'none', borderRadius: 4 }}>
            Reset Native Form
          </button>
        </div>
        <div style={{ marginTop: 15 }}>
          <div><strong>Current Native Value:</strong></div>
          <div>Selected Storage: {nativeValue || 'None'}</div>
          <div>Form Valid: {nativeValue ? 'true' : 'false'}</div>
          <div>Form Touched: {nativeTouched ? 'true' : 'false'}</div>
        </div>
      </form>

      {/* Testing instructions */}
      <div style={{ background: '#f5f5f5', padding: 15, borderRadius: 4, marginTop: 20 }}>
        <h3>Testing Instructions:</h3>
        <ol>
          <li><strong>Form Interaction:</strong> Select a storage option and fill in the customer name</li>
          <li><strong>Submit Test:</strong> Try submitting without selecting storage or entering name</li>
          <li><strong>Reset Form:</strong> Click "Reset Form" to clear all values and validation states</li>
          <li><strong>Clear Touched State:</strong> Click "Clear Touched State" to reset only the touched state without clearing values</li>
          <li><strong>Console Logging:</strong> Open browser DevTools console to see detailed form submission logs</li>
        </ol>
        <p><strong>Expected Behavior:</strong></p>
        <ul>
          <li><strong>Reset Form:</strong> Clears all values, resets touched state, and removes validation errors</li>
          <li><strong>Clear Touched State:</strong> Keeps values but resets the touched state (simulates programmatic reset)</li>
          <li><strong>Form Validation:</strong> Shows validation errors only after user interaction</li>
        </ul>
      </div>
    </div>
  );
}
